### ISSUE TITLE
mvn compile error

### ISSUE THREAD

**Issue by anshumanrai** [peteanderson80/SPICE#1]
I get the following compile error on doing mvn clean verify

Failed to execute goal on project spice: Could not resolve dependencies for project edu.anu.spice:spice:jar:1.0: The following artifacts could not be resolved: edu.cmu.meteor:Meteor:jar:1.5, edu.stanford.nlp:SceneGraphParser:jar:1.0:
Failure to find edu.cmu.meteor:Meteor:jar:1.5 in http://download.oracle.com/maven was cached in the local repository, resolution will not be reattempted until the update interval of oracleReleases has elapsed or updates are forced -> [Help 1]

**Comment by jackyyeh5111** [comment]
@anshumanrai How did you solve it?
I encounter just the same problem.

**Comment by ZishunYu** [comment]
I encountered the same issue as well. Does anyone have any idea how to solve this? Appreciate for any advice.

**Comment by ZishunYu** [comment]
I cleaned the build and rebuild and it works. Have no idea why tho.

**Comment by divyanshu092** [comment]
I am also facing this issue and rebuilding doesn't work in my case.
How should I solve this problem?

**Comment by vin30731** [comment]
Hi, I solved the exact same problem by the following step.
These are not the optimal steps, it just works for me in my case.
1. I add the following repository into pom.xml (This step solves the problem for edu.cmu.meteor:Meteor:jar:1.5)
    
        <repository>
      		<id>CogcompSoftware</id>
      		<name>CogcompSoftware</name>
      		<url>http://cogcomp.cs.illinois.edu/m2repo/</url>
    	</repository>
    
2. I directly install scenegraph-1.0.jar into my local repository using the following command (remember to change the file path)
    
        mvn install:install-file -Dfile=/home/vin30731/Desktop/SPICE/lib/scenegraph-1.0.jar -DgroupId=edu.stanford.nlp - 
        DartifactId=SceneGraphParser -Dversion=1.0 -Dpackaging=jar

**Comment by subake** [comment]
@vin30731 solution almost worked for me.

Had to directly install Meteor as well:
`mvn install:install-file -Dfile=./lib/meteor-1.5.jar -DgroupId=edu.cmu.meteor -DartifactId=Meteor -Dversion=1.5 -Dpackaging=jar`

And after that
`mvn clean verify`
