### ISSUE TITLE
About the metric

### ISSUE THREAD

**Issue by lindatan90** [peteanderson80/SPICE#3]
May I know how is cardinality evaluated?

**Comment by peteanderson80** [comment]
The scene graph parser identifies numerical modifiers and [parses them as attributes of objects](https://github.com/peteanderson80/SPICE/blob/ac6d9ce4c9c7212332d1325cc50ff0588918318b/src/main/java/edu/anu/spice/SpiceParser.java#L304-L315).

For the cardinality evaluation, we simply report the f-score for the attributes from one to ten, as shown [here](https://github.com/peteanderson80/SPICE/blob/ac6d9ce4c9c7212332d1325cc50ff0588918318b/src/main/java/edu/anu/spice/TupleFilter.java#L34-L35). 

Of course, larger numbers could be included as well, but numbers > 10 that appear in captions are usually the result of that number being visible in the scene as text. We wanted to focus on counting of objects. 

I will close this issue, but you can contact me by email if you have more questions.
