### ISSUE TITLE
Issue about Version of CORENLP

### ISSUE THREAD

**Issue by XChuanLee** [peteanderson80/SPICE#9]
sorry for the bothering.
I downloaded the lateest corenlp from https://stanfordnlp.github.io/CoreNLP/ .Is there any way to change version in the code?

**Comment by fntp** [comment]
....

**Comment by peteanderson80** [comment]
It hasn't been tested with later versions of CoreNLP. If you use the precompiled jar files from the project page a download script is provided for CoreNLP that references http://nlp.stanford.edu/software/stanford-corenlp-full-2015-12-09.zip.

**Comment by fntp** [comment]
Excuse me, brother, do you have any Twitter or telegram or Wechat account? ID? I'd like to chat with you! 

Please!













At 2021-02-22 14:08:39, "Peter Anderson" <notifications@github.com> wrote:

It hasn't been tested with later versions of CoreNLP. If you use the precompiled jar files from the project page a download script is provided for CoreNLP that references http://nlp.stanford.edu/software/stanford-corenlp-full-2015-12-09.zip.
